version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      PGDATA: /store/postgres
    volumes:
      - postgres:/store/postgres
    networks:
      - pg-net
    restart: unless-stopped
    ports:
      - "5432:5432"
#  pharmacy:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    networks:
#      - pg-net
#    depends_on:
#      - postgres
#      - redis
#      - migrations
#    ports:
#      - "9005:9005"
#    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-example@example.example}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD:-postgres}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pg-net
    restart: unless-stopped
    ports:
      - "8081:80"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${RD_PASSWORD:-redis}
    ports:
      - "6379:6379"
    volumes:
    - redis:/bitnami
  migrations:
    container_name: migrations
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - pg-net
    volumes:
        - ./migrations:/database
    command:
        [ "-path", "/database", "-database", "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-postgres}?sslmode=disable", "${MIGRATIONS_STATUS:-up}"]

volumes:
  postgres:
  redis:
  pgadmin:

networks:
  pg-net:
    driver: bridge