// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pharmacy.proto

package pharmacyproto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pharmacy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Pharmacy) Reset() {
	*x = Pharmacy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pharmacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pharmacy) ProtoMessage() {}

func (x *Pharmacy) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pharmacy.ProtoReflect.Descriptor instead.
func (*Pharmacy) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *Pharmacy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pharmacy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pharmacy) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type NewPharmacy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *NewPharmacy) Reset() {
	*x = NewPharmacy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPharmacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPharmacy) ProtoMessage() {}

func (x *NewPharmacy) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPharmacy.ProtoReflect.Descriptor instead.
func (*NewPharmacy) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *NewPharmacy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewPharmacy) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City   string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	House  string `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId int64 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Pharmacies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pharmacies []*Pharmacy `protobuf:"bytes,1,rep,name=pharmacies,proto3" json:"pharmacies,omitempty"`
}

func (x *Pharmacies) Reset() {
	*x = Pharmacies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pharmacies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pharmacies) ProtoMessage() {}

func (x *Pharmacies) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pharmacies.ProtoReflect.Descriptor instead.
func (*Pharmacies) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{4}
}

func (x *Pharmacies) GetPharmacies() []*Pharmacy {
	if x != nil {
		return x.Pharmacies
	}
	return nil
}

var File_pharmacy_proto protoreflect.FileDescriptor

var file_pharmacy_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x08, 0x50, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x55, 0x0a, 0x0b, 0x4e,
	0x65, 0x77, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x4b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22,
	0x55, 0x0a, 0x11, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x06,
	0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x22, 0x03, 0x18, 0x88, 0x27, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x47, 0x0a, 0x0a, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61,
	0x63, 0x69, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x52, 0x0a, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x65, 0x73, 0x32,
	0xab, 0x01, 0x0a, 0x0f, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61,
	0x72, 0x6d, 0x61, 0x63, 0x79, 0x12, 0x1c, 0x2e, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x50, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x70,
	0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x65, 0x73, 0x42, 0x13, 0x5a,
	0x11, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_proto_rawDescData = file_pharmacy_proto_rawDesc
)

func file_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pharmacy_proto_rawDescData)
	})
	return file_pharmacy_proto_rawDescData
}

var file_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pharmacy_proto_goTypes = []interface{}{
	(*Pharmacy)(nil),          // 0: pharmacyService.Pharmacy
	(*NewPharmacy)(nil),       // 1: pharmacyService.NewPharmacy
	(*Address)(nil),           // 2: pharmacyService.Address
	(*PaginationRequest)(nil), // 3: pharmacyService.PaginationRequest
	(*Pharmacies)(nil),        // 4: pharmacyService.Pharmacies
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_pharmacy_proto_depIdxs = []int32{
	2, // 0: pharmacyService.Pharmacy.address:type_name -> pharmacyService.Address
	2, // 1: pharmacyService.NewPharmacy.address:type_name -> pharmacyService.Address
	0, // 2: pharmacyService.Pharmacies.pharmacies:type_name -> pharmacyService.Pharmacy
	1, // 3: pharmacyService.PharmacyService.CreatePharmacy:input_type -> pharmacyService.NewPharmacy
	3, // 4: pharmacyService.PharmacyService.GetPharmacies:input_type -> pharmacyService.PaginationRequest
	5, // 5: pharmacyService.PharmacyService.CreatePharmacy:output_type -> google.protobuf.Empty
	4, // 6: pharmacyService.PharmacyService.GetPharmacies:output_type -> pharmacyService.Pharmacies
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pharmacy_proto_init() }
func file_pharmacy_proto_init() {
	if File_pharmacy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pharmacy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pharmacy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pharmacy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPharmacy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pharmacy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pharmacy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pharmacy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pharmacies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pharmacy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_proto = out.File
	file_pharmacy_proto_rawDesc = nil
	file_pharmacy_proto_goTypes = nil
	file_pharmacy_proto_depIdxs = nil
}
